kotlin.code.style=official

# The latest supported versions. Note, these are updated automatically from upgrade-major-versions.sh
IIU.release.version=262.10315.125
IIU.eap.version=263.3889.65

IIU.release.go_plugin.version=262.10315.125
IIU.eap.go_plugin.version=263.3889.65
GO.release.version=262.10315.160
GO.eap.version=263.3889.70
# The oldest supported versions.
IIU.from.version=251.23774.435
GO.from.version=251.23774.430
