kotlin.code.style=official

# The latest supported versions. Note, these are updated automatically from upgrade-major-versions.sh
IIU.release.version=261.22158.277
IIU.eap.version=261.23567.28

IIU.release.go_plugin.version=261.22158.277
IIU.eap.go_plugin.version=261.23567.28
GO.release.version=261.22158.291
GO.eap.version=261.23567.28
# The oldest supported versions.
IIU.from.version=251.23774.435
GO.from.version=251.23774.430
