on:
  schedule:
    - cron:  '0 * * * *'
name: Major version update
jobs:
  upgrade:
    name: Check for updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: ./bin/hermit env -r >> $GITHUB_ENV
      - run: ./upgrade-major-versions.sh
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto/major-update
          labels: automerge
          base: main
          title: "[Automatic] Upgrade of the major versions"
          # We need to use a separate token so that the PR will trigger tests.
          # See https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          token: ${{ steps.generate-token.outputs.token }}
