on:
  schedule:
    - cron:  '0 0 * * *'
name: Major version update
jobs:
  upgrade:
    name: Check for updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: ./bin/hermit env -r >> $GITHUB_ENV
      - run: ./upgrade-major-versions.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto/major-update
          labels: automerge
          base: main
          title: "[Automatic] Upgrade of the major versions"
