on:
  push:
    tags:
      - 'v*'
name: Release
jobs:
  deployable:
    name: Stable IJ Plugin
    strategy:
      matrix:
        release_type: [release, eap]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Init Hermit
        run: |
          ./bin/hermit env -r >> $GITHUB_ENV
          ./bin/hermit install -d
      - name: Test
        run: |
          ./bin/gradle test --info
      - name: Publish
        env:
          RELEASE_TYPE: ${{ matrix.release_type }}
          JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_PLUGIN_TOKEN }}
        run: |
          export IJ_PLUGIN_VERSION=$(git describe --tags --abbrev=0 | sed s,^v,,)
          echo "IJ_PLUGIN_VERSION=$IJ_PLUGIN_VERSION" >> $GITHUB_ENV

          ./bin/gradle patchPluginXml
          ./bin/gradle publishPlugin
