on:
  push:
    tags:
      - 'v*'
name: Release
jobs:
  deployable:
    name: Stable IJ Plugin
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Init Hermit
        run: |
          ./bin/hermit env >> $GITHUB_ENV
          ./bin/hermit install -d
      - name: Build IJ Plugin
        run: |
          export IJ_PLUGIN_VERSION=$(git rev-parse HEAD | sed s,^v,,)
          echo "IJ_PLUGIN_VERSION=$IJ_PLUGIN_VERSION" >> $GITHUB_ENV
          make PLUGIN_VERSION=$IJ_PLUGIN_VERSION PLUGIN_CHANNEL=stable